import fs from 'node:fs';import path from 'node:path';import sharp from 'sharp';import { SITE,assert,read,readJson,write,writeJson } from '../lib/core.js';
type LogoState={mobile_width:number;desktop_width:number;mobile_source:[number,number];mobile_bbox:[number,number,number,number];desktop_source:[number,number];desktop_bbox:[number,number,number,number]};
async function bbox(file:string):Promise<{size:[number,number];box:[number,number,number,number]}> {const {data,info}=await sharp(file).ensureAlpha().raw().toBuffer({resolveWithObject:true});let minX=info.width,minY=info.height,maxX=-1,maxY=-1;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const a=data[(y*info.width+x)*info.channels+3]??0;if(a>8){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}}if(maxX<0)return {size:[info.width,info.height],box:[0,0,info.width,info.height]};return {size:[info.width,info.height],box:[minX,minY,maxX+1,maxY+1]};}
export async function measureSystemLogo():Promise<void>{const mobile=path.join(SITE,'_critical-media/mobile-logo.webp'),desktop=path.join(SITE,'_chrome-media/desktop-logo.webp');assert(fs.existsSync(mobile)&&fs.existsSync(desktop),'system-logo optical calibration inputs are missing');const m=await bbox(mobile),d=await bbox(desktop);const mw=Math.round(333*(m.box[2]-m.box[0])/m.size[0]),dw=d.box[2]-d.box[0];assert(mw>=72&&mw<=240,`unexpected mobile logo optical width ${mw}px`);assert(dw>=160&&dw<=280,`unexpected desktop logo optical width ${dw}px`);writeJson(path.join(SITE,'.system-logo-optics.json'),{mobile_source:m.size,mobile_bbox:m.box,mobile_width:mw,desktop_source:d.size,desktop_bbox:d.box,desktop_width:dw} satisfies LogoState);}
export function applySystemLogoOptics():void{const index=path.join(SITE,'index.html'),stateFile=path.join(SITE,'.system-logo-optics.json');assert(fs.existsSync(index)&&fs.existsSync(stateFile),'system-logo optical calibration state is missing');const s=readJson<LogoState>(stateFile),mw=s.mobile_width,dw=s.desktop_width;let html=read(index);const start=html.indexOf('<style id="sc-system-brand-css">'),endStart=html.indexOf('</style>',start);assert(start>=0&&endStart>=0,'system logo critical CSS was not generated');const css=`<style id="sc-system-brand-css">
body.sushiShop .sc-system-brand-logo{display:block!important;width:auto!important;height:auto!important;margin:0!important;padding:0!important;opacity:1!important;visibility:visible!important;object-fit:contain!important;object-position:center center!important;filter:invert(1)!important;transform:none!important;transition:filter var(--sc-motion-theme,560ms) cubic-bezier(.45,0,.55,1)!important}
html[data-sc-theme-resolved='dark'] body.sushiShop .sc-system-brand-logo{filter:none!important}
@media(min-width:993px){body.sushiShop .topBar.newVer17topBar{background-color:var(--sc-color-surface)!important;color:var(--sc-color-ink)!important}body.sushiShop .newVer17topBar span,body.sushiShop .newVer17topBar a,body.sushiShop .newVer17topBar .dropdown a,body.sushiShop .newVer17topBar .top-reservas span a,body.sushiShop .newVer17topBar .socialTop .fa{color:var(--sc-color-ink)!important}body.sushiShop .newVer17topBar .brandCol,body.sushiShop .newVer17topBar .main-nav,body.sushiShop .newVer17topBar .nav{background-color:transparent!important}body.sushiShop .newVer17topBar .brand:has(.sc-system-brand-logo){box-sizing:border-box!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;width:${dw}px!important;max-width:${dw}px!important;height:55px!important;max-height:55px!important;margin:0 auto!important;padding:0!important;line-height:0!important;vertical-align:top!important}body.sushiShop .newVer17topBar .brand:has(.sc-system-brand-logo)>a{display:flex!important;position:static!important;top:auto!important;left:auto!important;align-items:center!important;justify-content:center!important;width:100%!important;height:100%!important;margin:0!important;padding:0!important;line-height:0!important;transform:none!important}body.sushiShop .newVer17topBar .sc-system-brand-logo{width:${dw}px!important;max-width:${dw}px!important;height:auto!important;max-height:45px!important}}
@media(max-width:992px){body.sushiShop .brandOnlyMobile:has(.sc-system-brand-logo){display:flex!important;position:relative!important;align-items:center!important;justify-content:center!important;height:var(--sc-mobile-header-height,100px)!important;margin:0!important;padding:0!important}body.sushiShop .brandOnlyMobile:has(.sc-system-brand-logo)>a{display:flex!important;position:static!important;top:auto!important;right:auto!important;bottom:auto!important;left:auto!important;align-items:center!important;justify-content:center!important;width:${mw}px!important;max-width:calc(100vw - 96px)!important;height:100%!important;margin:0!important;padding:0!important;line-height:0!important;transform:none!important}body.sushiShop .brandOnlyMobile .sc-system-brand-logo{width:${mw}px!important;max-width:100%!important;height:auto!important;max-height:45px!important;aspect-ratio:312/45!important}}
</style>`;html=html.slice(0,start)+css+html.slice(endStart+'</style>'.length);write(index,html);fs.rmSync(stateFile);}
