import path from 'node:path';
import { SITE, assert, escapeRegExp, write } from '../../lib/core.js';

const LEGACY_CRITICAL=new Set(['_css_dev/bootstrap.min.css','_css_dev/fnt-helvlig.css','_css_dev/fontBar.css','_css_dev/slicknav__q_dd9216b6.css','_css_dev/styles.css','_css_dev/styles_newver17.css','css/styles_shop__q_a48cd660.css','css/_aux__q_a48cd660.css']);
const OVERRIDE_CRITICAL=new Set(['./core/variables.css','./core/theme.css','./core/a11y.css','./features/catalog/catalog.css','./components/category-nav/desktop.css','./components/category-nav/mobile.css','./components/category-nav/controls.css','./core/prepaint.css','./core/performance.css','./core/no-loading-state.css','./components/product-card/image-ratio.css','./features/catalog/layout.css','./components/section-heading/layout.css','./components/product-card/layout.css','./components/product-card/content.css','./components/product-card/pricing.css','./components/catalog-tools/catalog-tools.css','./components/catalog-tools/theme.css','./components/catalog-tools/view-stability.css','./components/section-heading/section-heading.css','./components/section-heading/responsive.css','./components/mobile-header/mobile-header.css','./components/mobile-header/state-icon.css','./components/category-nav/compatibility.css','./features/image-preloader/image-preloader.css']);

function minCss(value:string):string{return value.replace(/\/\*(?!\!)[\s\S]*?\*\//g,'').replace(/[\t\r\n]+/g,' ').replace(/ {2,}/g,' ').trim();}
function toPagesUrls(css:string):string{return css.replace(/url\(\s*(?<quote>["']?)(?<value>.*?)(?:\k<quote>)\s*\)/gi,(full:string,...args:unknown[])=>{const groups=args.at(-1) as {quote?:string;value?:string}|undefined,value=(groups?.value??'').trim(),quote=groups?.quote??'';if(!value||/^(?:data:|[a-z][a-z0-9+.-]*:|\/\/|\/|#)/i.test(value))return full;const match=/^(?<path>[^?#]+)(?<suffix>[?#].*)?$/.exec(value);if(!match?.groups?.path)return full;return `url(${quote}${path.posix.normalize(path.posix.join('..',match.groups.path))}${match.groups.suffix??''}${quote})`;});}
export function splitCss(html:string):{html:string;criticalBytes:number;deferredBytes:number}{const re=/<style id="sc-pages-critical-css">(?<css>[\s\S]*?)<\/style>/i,match=re.exec(html);assert(match?.groups?.css&&match.index!==undefined,'current critical CSS block missing');const css=match.groups.css,marker=/^\/\* origen: (?<name>.*?) \*\/\s*/gm,markers=[...css.matchAll(marker)];assert(markers.length>0,'CSS source markers missing');const critical:string[]=[],deferred:string[]=[];for(let i=0;i<markers.length;i++){const item=markers[i]!,start=item.index!,end=markers[i+1]?.index??css.length,name=(item.groups?.name??'').replace(/\s+\(omitido:.*?\)$/,'');const chunk=css.slice(start,end);if(LEGACY_CRITICAL.has(name)||OVERRIDE_CRITICAL.has(name))critical.push(chunk);else deferred.push(toPagesUrls(chunk));}const roboto=/<style id="sc-roboto-font-css">(?<css>[\s\S]*?)<\/style>\s*/i.exec(html);if(roboto?.groups?.css)deferred.push(roboto.groups.css);const c=minCss(critical.join('\n')),d=minCss(deferred.join('\n'));const deferredFile=path.join(SITE,'_pages/deferred.css');write(deferredFile,d+'\n');html=html.slice(0,match.index)+`<style id="sc-pages-critical-css">${c}</style>`+html.slice(match.index+match[0].length);if(roboto?.index!==undefined)html=html.slice(0,roboto.index)+html.slice(roboto.index+roboto[0].length);html=html.replace(/<link\b(?=[^>]*rel=["']preconnect["'])(?=[^>]*href=["']https:\/\/fonts\.(?:googleapis|gstatic)\.com\/?["'])[^>]*>\s*/gi,'');html=html.replace(/(<link\b(?=[^>]*rel=["']preload["'])(?=[^>]*AcuminPro-(?:Regular|Semibold)\.woff2)(?<attrs>[^>]*))>/gi,(_all:string,prefix:string,...args:unknown[])=>{const groups=args.at(-1) as {attrs?:string}|undefined;return prefix+(groups?.attrs&&/fetchpriority=/i.test(groups.attrs)?'':' fetchpriority="low"')+'>';});return {html,criticalBytes:c.length,deferredBytes:d.length};}
export function criticalMedia(html:string):string{const logo='https://www.sushiclub.com.ar/gfx/web-sushiclub2_black_m2.png';html=html.replace(new RegExp(`<link\\b(?=[^>]*rel=["']preload["'])(?=[^>]*as=["']image["'])(?=[^>]*href=["']${escapeRegExp(logo)}["'])[^>]*>\\s*`,'i'),'');const preload=/(<link\b(?=[^>]*rel=["']preload["'])(?=[^>]*as=["']image["'])(?=[^>]*banner_shop)[^>]*)(>)/i.exec(html);if(preload?.index!==undefined&&!/media=/i.test(preload[1]??''))html=html.slice(0,preload.index)+(preload[1]??'')+' media="(min-width: 993px)"'+(preload[2]??'>')+html.slice(preload.index+preload[0].length);const image=/(<img\b(?=[^>]*class=["'][^"']*\bimgBannerShop\b[^"']*["'])(?<attrs>[^>]*))>/i.exec(html);if(image?.groups?.attrs&&image.index!==undefined){const attrs=image.groups.attrs.replace(/\s+fetchpriority=["'][^"']*["']/gi,'')+' fetchpriority="auto"';html=html.slice(0,image.index)+`<img${attrs}>`+html.slice(image.index+image[0].length);}return html;}
