import path from 'node:path';
import { SITE, assert, escapeRegExp, read, write } from '../../lib/core.js';

const RUNTIME=['js/jquery-2.1.0.min.js','_pages/legacy.js','_js_dev/main-legacy.js','override/main.js','_pages/shop.js'] as const;

export function removeRuntime(html:string,sha:string):string{for(const runtime of RUNTIME){const suffix=runtime.startsWith('js/jquery')?'':`\\?v=${escapeRegExp(sha)}`,re=new RegExp(`<script\\b(?=[^>]*src=["']${escapeRegExp(runtime)}${suffix}["'])[^>]*>\\s*<\\/script>\\s*`,'i');const matches=html.match(new RegExp(re.source,'gi'))??[];assert(matches.length===1,`runtime tag mismatch: ${runtime}=${matches.length}`);html=html.replace(re,'');}return html;}
export function queueInline(html:string):string{for(const marker of ['function isValidEmailAddress(emailAddress)','var keepSessionAlive = function()']){const scripts=[...html.matchAll(/<script(?<attrs>[^>]*)>(?<body>[\s\S]*?)<\/script>/gi)],match=scripts.find((item)=>(item.groups?.body??'').includes(marker));assert(match?.groups?.body&&match.index!==undefined,`inline marker missing: ${marker}`);let body=match.groups.body;const wrapper=/^\s*document\.addEventListener\('DOMContentLoaded',function\(\)\{\s*(?<inner>[\s\S]*?)\s*\},\{once:true\}\);\s*$/.exec(body);if(wrapper?.groups?.inner)body=wrapper.groups.inner;const replacement=`<script>window.__scAfterRuntime=window.__scAfterRuntime||[];window.__scAfterRuntime.push(function(){\n${body}\n});</script>`;html=html.slice(0,match.index)+replacement+html.slice(match.index+match[0].length);}return html;}
export function patchRuntime():void{const shopFile=path.join(SITE,'_pages/shop.js'),legacyFile=path.join(SITE,'_pages/legacy.js');let shop=read(shopFile);const startup=/\$\(function\(\)\s*\{\s*PS_initSearch\(\);\s*makeToolTips\(\);\s*shopCopyMobileNav\(\);\s*(?:if \(window\.moment\)\s*)?moment\.locale\('es'\);\s*shop_JSModales\(\);\s*shop_imgLiquids\(\);\s*shop_normalizeCols\(\);\s*dropdowntogglewOver\(\);\s*scrllAnim\(\);\s*JSgoMenu\(\);\s*JSgroupButtons\(\);\s*JSTopDropDown\(\);\s*\}\);/s;assert((shop.match(new RegExp(startup.source,'gs'))??[]).length===1,'shop startup callback mismatch');shop=shop.replace(startup,"$(function() {\n\tshopCopyMobileNav();\n\tif (window.moment) moment.locale('es');\n\tvar jobs=[PS_initSearch,makeToolTips,shop_JSModales,dropdowntogglewOver,scrllAnim,JSgoMenu,JSgroupButtons,JSTopDropDown];\n\tfor(var i=0;i<jobs.length;i++)(function(fn,delay){setTimeout(fn,delay)})(jobs[i],i*18);\n});");for(const name of ['shop_imgLiquids','shop_normalizeCols']){const re=new RegExp(`\\nfunction ${name}\\(\\)\\s*\\{[\\s\\S]*?\\n\\}\\n`);assert((shop.match(new RegExp(re.source,'g'))??[]).length===1,`cannot remove ${name}`);shop=shop.replace(re,'\n');}write(shopFile,shop);let legacy=read(legacyFile);const normalize=/\/\*Knormalize_+\*\/\s*function Knormalize\(obj\)\s*\{[\s\S]*?\n\}\s*/;assert((legacy.match(new RegExp(normalize.source,'g'))??[]).length===1,'cannot remove Knormalize');legacy=legacy.replace(normalize,'');write(legacyFile,legacy);}
export function stripMaps():void{for(const rel of ['_pages/legacy.js','_pages/shop.js','_js_dev/main-legacy.js','override/main.js']){const file=path.join(SITE,rel);write(file,read(file).replace(/^\s*\/\/[@#]\s*sourceMappingURL=.*$/gm,'').replace(/\/\*# sourceMappingURL=[\s\S]*?\*\//g,''));}}
