/* Coordina mejora progresiva, observadores y relayout de tarjetas. */
(function(){
'use strict';
var SC=window.SCOverride,U=SC&&SC.utils,C=SC&&SC.config,S=C&&C.selectors,P=SC&&SC.productCardContent,A=SC&&SC.productCardA11y,D=SC&&SC.productCardData;if(!SC||!U||!C||!P||!A||!D||SC.__productCardBooted)return;SC.__productCardBooted=true;
var ready=U.ready,desktopQuery=C.queries.desktop,cardObserver:MutationObserver|null=null,resizeObserver:ResizeObserver|null=null,resizeFallback=false,cardRaf=0,initialIdle=0,initialTimer=0,initialQueue:HTMLElement[]=[],initialDone=false,initialized=false,INITIAL_BATCH=10,INITIAL_BUDGET_MS=5,INITIAL_IDLE_TIMEOUT=1200;
function enhanceCard(card:HTMLElement|null|undefined):void{if(!card)return;var link=card.querySelector<HTMLElement>(S.productLink);if(link){P.installFlavorRow(link);A.enhanceLink(link);}if(P.ensureDescriptionCopy)P.ensureDescriptionCopy(card);}
function refreshCards():void{A.enhanceHeadings();P.installTraitReferences();document.querySelectorAll<HTMLElement>(S.productCards).forEach(enhanceCard);P.scheduleDescriptionMeasure();if(SC.motion&&SC.motion.refresh)SC.motion.refresh(60);}
function scheduleCardRefresh():void{if(cardRaf)return;cardRaf=requestAnimationFrame(function(){cardRaf=0;refreshCards();});}
function observeCards():void{var container=document.querySelector<HTMLElement>(S.container);if(!container||cardObserver)return;cardObserver=new MutationObserver(function(records:MutationRecord[]){for(var i=0;i<records.length;i++){var record=records[i];if(!record)continue;for(var j=0;j<record.addedNodes.length;j++){var node=record.addedNodes[j];if(!(node instanceof Element))continue;if(node.matches(S.productCard)||node.querySelector(S.productCard)){scheduleCardRefresh();return;}}}});cardObserver.observe(container,{childList:true,subtree:true});}
function observeResize():void{var container=document.querySelector<HTMLElement>(S.container);if(!container)return;if(window.ResizeObserver){resizeObserver=new ResizeObserver(function(){P.scheduleDescriptionMeasure();});resizeObserver.observe(container);}else if(!resizeFallback){resizeFallback=true;window.addEventListener('resize',P.scheduleDescriptionMeasure,{passive:true});}}
function finishInitialWork():void{if(initialDone)return;initialDone=true;observeCards();observeResize();P.scheduleDescriptionMeasure();}
function cancelInitialWork():void{if(initialIdle&&window.cancelIdleCallback)window.cancelIdleCallback(initialIdle);if(initialTimer)clearTimeout(initialTimer);initialIdle=initialTimer=0;initialQueue=[];}
function runInitialBatch(deadline?:IdleDeadline|null):void{initialIdle=0;initialTimer=0;if(!initialized)return;var start=performance.now(),count=0;while(initialQueue.length&&count<INITIAL_BATCH){if(deadline&&deadline.timeRemaining()<1&&!deadline.didTimeout)break;if(performance.now()-start>INITIAL_BUDGET_MS)break;enhanceCard(initialQueue.shift());count++;}if(initialQueue.length)scheduleInitialBatch();else finishInitialWork();}
function scheduleInitialBatch():void{if(!initialized||initialIdle||initialTimer)return;if(typeof window.requestIdleCallback==='function'){initialIdle=window.requestIdleCallback(runInitialBatch,{timeout:INITIAL_IDLE_TIMEOUT});return;}initialTimer=window.setTimeout(function(){runInitialBatch(null);},32);}
function startIncrementalEnhancement():void{initialDone=false;A.enhanceHeadings();P.installTraitReferences();initialQueue=Array.prototype.slice.call(document.querySelectorAll(S.productCard)) as HTMLElement[];var critical=desktopQuery.matches?8:4;while(initialQueue.length&&critical-->0)enhanceCard(initialQueue.shift());if(initialQueue.length)scheduleInitialBatch();else finishInitialWork();}
function breakpoint():void{if(initialized)refreshCards();}
function init():void{if(initialized)return;initialized=true;startIncrementalEnhancement();if(desktopQuery.addEventListener)desktopQuery.addEventListener('change',breakpoint);else desktopQuery.addListener(breakpoint);}
function destroy():void{if(!initialized)return;initialized=false;if(cardObserver)cardObserver.disconnect();if(resizeObserver){resizeObserver.disconnect();resizeObserver=null;}if(resizeFallback){window.removeEventListener('resize',P.scheduleDescriptionMeasure);resizeFallback=false;}if(cardRaf){cancelAnimationFrame(cardRaf);cardRaf=0;}cancelInitialWork();if(P.cancelDescriptionMeasure)P.cancelDescriptionMeasure();if(desktopQuery.removeEventListener)desktopQuery.removeEventListener('change',breakpoint);else desktopQuery.removeListener(breakpoint);}
ready(init);SC.productCard={imageSource:D.imageSource,traitLabels:D.traitLabels,buildTraitGroup:D.buildTraitGroup,enhanceProductLinks:A.enhanceAll,refresh:refreshCards,repair:scheduleCardRefresh,init:init,destroy:destroy};
})();
