/* SushiClub DevTools audit. Paste entire file in Console. Re-run after reproducing an issue with: await __SC_AUDIT__.copy() */
void (async()=>{
'use strict';
const K='__SC_AUDIT__',V='1.0.0',T=6500,MAX=300,C=20;
if(window[K]?.installed){await window[K].copy();return}
const raw={log:console.log,warn:console.warn,error:console.error},state={since:new Date().toISOString(),events:[],report:''};
const txt=(v,n=1200)=>{let s;try{s=typeof v==='string'?v:JSON.stringify(v)}catch{s=String(v)}s=String(s??'').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n)+'…':s};
const er=e=>e instanceof Error?txt(e.stack||`${e.name}: ${e.message}`):txt(e),abs=(v,b=location.href)=>{try{return new URL(v,b).href}catch{return String(v||'')}};
const sel=e=>{if(!(e instanceof Element))return'';if(e.id)return'#'+CSS.escape(e.id);const a=[];for(let n=e;n&&n.nodeType===1&&a.length<4;n=n.parentElement)a.unshift(n.localName+[...n.classList].slice(0,2).map(c=>'.'+CSS.escape(c)).join(''));return a.join(' > ')};
const cssUrls=(s,b)=>{const a=[];let m,r=/url\(\s*(['"]?)(.*?)\1\s*\)/gi;while((m=r.exec(String(s||''))))if(m[2]&&!/^data:|^blob:/.test(m[2]))a.push(abs(m[2],b));return a};
const srcset=(s,b)=>String(s||'').split(',').map(x=>x.trim().split(/\s+/)[0]).filter(Boolean).map(x=>abs(x,b));
const cap=(k,m,d={})=>state.events.push({k,m:txt(m),d,at:new Date().toISOString()});
const onerr=e=>{const t=e.target;if(t&&t!==window&&t instanceof Element)cap('resource-error','Resource error',{selector:sel(t),url:t.currentSrc||t.src||t.href||''});else cap('js-error',e.message||'JavaScript error',{source:e.filename||'',line:e.lineno||0,column:e.colno||0,error:er(e.error)})};
const onrej=e=>cap('unhandled-rejection','Unhandled promise rejection',{reason:er(e.reason)});
window.addEventListener('error',onerr,true);window.addEventListener('unhandledrejection',onrej,true);
console.error=(...a)=>{cap('console-error',a.map(txt).join(' '));raw.error.apply(console,a)};console.warn=(...a)=>{cap('console-warn',a.map(txt).join(' '));raw.warn.apply(console,a)};
const delay=(ms,msg='timeout')=>new Promise((_,r)=>setTimeout(()=>r(new Error(msg)),ms));
const copy=async s=>{try{await navigator.clipboard.writeText(s);return}catch{}const a=document.createElement('textarea');a.value=s;a.readOnly=true;Object.assign(a.style,{position:'fixed',opacity:'0',left:'-9999px'});document.documentElement.appendChild(a);a.select();const ok=document.execCommand('copy');a.remove();if(!ok)throw Error('copy failed')};
const pool=async(a,fn)=>{const q=[...a];await Promise.all(Array.from({length:Math.min(C,q.length)},async()=>{while(q.length)await fn(q.shift())}))};
const probe=u=>new Promise(res=>{const i=new Image();let done=false;const end=x=>{if(done)return;done=true;clearTimeout(timer);i.onload=i.onerror=null;res(x)},timer=setTimeout(()=>end({ok:false,why:'timeout'}),T);i.onload=()=>end({ok:i.naturalWidth>0&&i.naturalHeight>0,w:i.naturalWidth,h:i.naturalHeight});i.onerror=()=>end({ok:false,why:'load-error'});i.decoding='async';i.src=u});
function readCss(){const fonts=[],assets=new Set,unread=[],seen=new Set;function walk(s){if(!s||seen.has(s))return;seen.add(s);let rules;try{rules=s.cssRules}catch(e){unread.push({href:s.href||'(inline)',error:er(e)});return}for(const r of rules||[]){if(r.type===CSSRule.IMPORT_RULE&&r.styleSheet)walk(r.styleSheet);if(r.type===CSSRule.FONT_FACE_RULE){const family=String(r.style.getPropertyValue('font-family')||'').replace(/^['"]|['"]$/g,'').trim(),src=r.style.getPropertyValue('src')||'';fonts.push({family,style:r.style.getPropertyValue('font-style')||'normal',weight:r.style.getPropertyValue('font-weight')||'normal',urls:cssUrls(src,s.href||location.href)})}for(const u of cssUrls(r.cssText||'',s.href||location.href))assets.add(u)}}for(const s of document.styleSheets)walk(s);return{fonts,assets,unread}}
async function audit(){const start=performance.now(),issues=[],seen=new Set,add=(sev,code,msg,d={})=>{const k=`${sev}|${code}|${msg}|${d.url||''}|${d.selector||''}`;if(!seen.has(k)){seen.add(k);issues.push({sev,code,msg,d})}};
const nav=performance.getEntriesByType('navigation')[0],res=performance.getEntriesByType('resource');for(const r of res){const s=Number(r.responseStatus||0);if(s>=400)add('ERROR','HTTP_'+s,'Resource returned HTTP '+s,{url:r.name,initiator:r.initiatorType})}
const imgs=[...document.images];for(const i of imgs){const u=i.currentSrc||i.src||i.getAttribute('data-src')||'';if(i.complete&&u&&i.naturalWidth===0)add('ERROR','BROKEN_IMAGE','Image has no usable pixels',{selector:sel(i),url:abs(u)});if(!i.complete&&u)add('WARNING','IMAGE_PENDING','Image is still loading',{selector:sel(i),url:abs(u)})}
const styles=[...document.querySelectorAll('link[rel~="stylesheet"]')];for(const l of styles)if(!l.sheet)add('ERROR','STYLESHEET_NOT_LOADED','Stylesheet did not attach',{selector:sel(l),url:abs(l.href)});
const ids=new Map;for(const e of document.querySelectorAll('[id]')){if(!ids.has(e.id))ids.set(e.id,[]);ids.get(e.id).push(e)}for(const[id,a]of ids)if(a.length>1)add('ERROR','DUPLICATE_ID','Duplicate id: '+id,{count:a.length,selectors:a.slice(0,8).map(sel)});
for(const a of document.querySelectorAll('a[href^="#"]')){const h=a.getAttribute('href');if(!h||h==='#')continue;let id=h.slice(1);try{id=decodeURIComponent(id)}catch{}if(id&&!document.getElementById(id))add('ERROR','BROKEN_FRAGMENT','Missing fragment target: '+h,{selector:sel(a)})}
const css=readCss();for(const x of css.unread)add('INFO','CSSOM_UNREADABLE','Stylesheet CSSOM is cross-origin/unreadable',x);try{await Promise.race([document.fonts.ready,delay(T,'document.fonts.ready timeout')])}catch(e){add('WARNING','FONT_SET_TIMEOUT','document.fonts.ready timed out',{error:er(e)})}
const used=new Set;for(const e of [...document.querySelectorAll('body, body *')].slice(0,3500))for(const f of getComputedStyle(e).fontFamily.split(','))used.add(f.replace(/^['"]|['"]$/g,'').trim().toLowerCase());
const fm=new Map,tests=[];for(const f of css.fonts){const k=`${f.family}|${f.style}|${f.weight}`;if(f.family&&!fm.has(k))fm.set(k,f)}for(const f of [...fm.values()].slice(0,100)){let loaded=[],why='';const family=f.family.replace(/"/g,'\\"');try{loaded=await Promise.race([document.fonts.load(`${f.style} ${f.weight} 16px "${family}"`,'Hamburgefontsiv'),delay(T,'font timeout')])}catch(e){why=er(e)}const ok=Boolean(loaded?.length),isUsed=used.has(f.family.toLowerCase());tests.push({...f,ok,used:isUsed});if(!ok)add(isUsed?'ERROR':'WARNING','FONT_LOAD_FAILED',`Font did not load: ${f.family} ${f.weight}`,{family:f.family,style:f.style,weight:f.weight,urls:f.urls,error:why})}
for(const f of document.fonts)if(f.status==='error')add('ERROR','FONT_FACE_ERROR','FontFace is in error state: '+f.family,{family:f.family,style:f.style,weight:f.weight});
const iu=new Set,addImg=v=>{const u=abs(v);if(u&&!/^data:|^blob:/.test(u)&&/\.(?:png|jpe?g|gif|webp|avif|bmp|ico|svg)(?:[?#].*)?$/i.test(u))iu.add(u)};for(const i of imgs){addImg(i.currentSrc||i.src);addImg(i.getAttribute('data-src'));addImg(i.getAttribute('data-lazy'));for(const u of srcset(i.getAttribute('srcset'),location.href))addImg(u)}for(const s of document.querySelectorAll('source[srcset]'))for(const u of srcset(s.getAttribute('srcset'),location.href))addImg(u);for(const v of document.querySelectorAll('video[poster]'))addImg(v.poster);for(const u of css.assets)addImg(u);for(const e of [...document.querySelectorAll('body, body *')].slice(0,3500)){const s=getComputedStyle(e);for(const u of cssUrls(`${s.backgroundImage} ${s.listStyleImage} ${s.borderImageSource}`,location.href))addImg(u)}
const all=[...iu],probes=all.slice(0,MAX);if(all.length>probes.length)add('WARNING','IMAGE_PROBE_LIMIT','Not every discovered image URL was actively probed',{discovered:all.length,probed:probes.length});await pool(probes,async u=>{const r=await probe(u);if(!r.ok)add('ERROR','IMAGE_URL_FAILED','Image URL failed active browser load test',{url:u,reason:r.why||'invalid-dimensions',width:r.w||0,height:r.h||0})});
for(const e of state.events)add(e.k==='console-warn'?'WARNING':'ERROR','CAPTURED_'+e.k.toUpperCase().replace(/-/g,'_'),e.m,e.d);
const ord={CRITICAL:0,ERROR:1,WARNING:2,INFO:3};issues.sort((a,b)=>ord[a.sev]-ord[b.sev]||a.code.localeCompare(b.code));const n={CRITICAL:0,ERROR:0,WARNING:0,INFO:0};for(const i of issues)n[i.sev]++;
const out=[];out.push(`SUSHICLUB RUNTIME AUDIT v${V}`,`URL: ${location.href}`,`Generated: ${new Date().toISOString()}`,`readyState: ${document.readyState}`,`Viewport: ${innerWidth}x${innerHeight}@${devicePixelRatio}x`,`User-Agent: ${navigator.userAgent}`);if(nav)out.push(`Navigation: DOMContentLoaded=${Math.round(nav.domContentLoadedEventEnd)}ms load=${Math.round(nav.loadEventEnd)}ms transfer=${nav.transferSize}B`);out.push(`Audit duration: ${Math.round(performance.now()-start)}ms`,'','NOTE: JS cannot read console/errors that happened before this script was pasted. Current DOM/resource/font/image state is tested directly; later errors are captured.','',`SUMMARY: CRITICAL=${n.CRITICAL} ERROR=${n.ERROR} WARNING=${n.WARNING} INFO=${n.INFO}`,`SCANNED: resources=${res.length} images=${imgs.length} imageURLs=${all.length}/${probes.length} stylesheets=${styles.length} fontRules=${css.fonts.length} captured=${state.events.length}`);
for(const sev of['CRITICAL','ERROR','WARNING','INFO']){const g=issues.filter(x=>x.sev===sev);out.push('',`===== ${sev} (${g.length}) =====`);if(!g.length)out.push('(none)');g.forEach((x,j)=>{out.push(`[${sev[0]}${String(j+1).padStart(3,'0')}] ${x.code} | ${x.msg}`);for(const[k,v]of Object.entries(x.d||{}))if(v!==''&&v!=null)out.push(`  ${k}: ${txt(v,1800)}`)})}
out.push('','===== FONT TESTS =====');if(!tests.length)out.push('(none found in readable CSS)');for(const f of tests)out.push(`${f.ok?'OK':'FAIL'} | ${f.family} | style=${f.style} weight=${f.weight} used=${f.used} | ${f.urls.join(', ')||'(no url)'}`);out.push('','===== USAGE =====','After reproducing an interaction issue: await __SC_AUDIT__.copy()','Cleanup: __SC_AUDIT__.stop()');state.report=out.join('\n');return{report:state.report,counts:n,issues,tests}}
const api={installed:true,version:V,state,run:audit,async copy(){const r=await audit();await copy(r.report);raw.log.call(console,`SushiClub audit copied. CRITICAL=${r.counts.CRITICAL} ERROR=${r.counts.ERROR} WARNING=${r.counts.WARNING} INFO=${r.counts.INFO}`);raw.log.call(console,r.report);return r.report},stop(){window.removeEventListener('error',onerr,true);window.removeEventListener('unhandledrejection',onrej,true);console.error=raw.error;console.warn=raw.warn;delete window[K];raw.log.call(console,'SushiClub auditor removed.')}};window[K]=api;try{await api.copy()}catch(e){raw.error.call(console,'SushiClub audit failed:',e)}
})();
