(function(){
'use strict';
var SC=window.SCOverride,U=SC&&SC.utils,C=SC&&SC.config,S=C&&C.selectors,V=SC&&SC.productModalView,A=SC&&SC.productModalA11y,M=SC&&SC.productModalMotion;if(!SC||!U||!V||!A||!M||SC.__productModalBooted)return;SC.__productModalBooted=true;
var ready=U.ready,activeModal:HTMLElement|null=null,activeLink:HTMLElement|null=null,closingModal:HTMLElement|null=null,closingLink:HTMLElement|null=null,previousFocus:HTMLElement|null=null,releaseBackground:(()=>void)|null=null,closingRelease:(()=>void)|null=null,closingRestore:HTMLElement|null=null,openRaf=0,initialized=false;
function noop():void{}
function focus(node:HTMLElement|null):void{if(!node||!document.documentElement.contains(node))return;try{node.focus({preventScroll:true});}catch(_){node.focus();}}
function cancelOpenRaf():void{if(openRaf){cancelAnimationFrame(openRaf);openRaf=0;}}
function buildModal(link:HTMLElement):HTMLElement|null{return V.build(link);}
function finishClose(modal:HTMLElement,restoreFocus:boolean):void{if(closingModal!==modal)return;if(M.cancel)M.cancel(modal);if(modal.parentNode)modal.parentNode.removeChild(modal);document.body.classList.remove('sc-product-modal-open');var release=closingRelease||noop,restore=closingRestore;closingModal=null;closingLink=null;closingRelease=null;closingRestore=null;release();if(restoreFocus!==false)focus(restore);}
function resumeClosingModal(link:HTMLElement):boolean{if(!closingModal||closingLink!==link)return false;var modal:HTMLElement=closingModal;closingModal=null;closingLink=null;activeModal=modal;activeLink=link;previousFocus=closingRestore||link;releaseBackground=closingRelease||noop;closingRestore=null;closingRelease=null;document.body.classList.add('sc-product-modal-open');modal.classList.add('is-visible');M.reopen(modal,link);focus(modal.querySelector<HTMLElement>('.sc-product-modal__close'));return true;}
function closeModal(event?:Event):void{if(event)event.preventDefault();if(!activeModal)return;cancelOpenRaf();var modal=activeModal;closingRestore=previousFocus;closingRelease=releaseBackground||noop;closingLink=activeLink;activeModal=null;activeLink=null;closingModal=modal;previousFocus=null;releaseBackground=null;M.close(modal,function():void{finishClose(modal,true);});}
function openModal(link:HTMLElement):void{if(activeModal||!link)return;if(closingModal){if(resumeClosingModal(link))return;finishClose(closingModal,false);}var built=buildModal(link);if(!built)return;var modal:HTMLElement=built;previousFocus=link;document.body.appendChild(modal);document.body.classList.add('sc-product-modal-open');activeModal=modal;activeLink=link;releaseBackground=A.lockBackground(modal)||noop;focus(modal.querySelector<HTMLElement>('.sc-product-modal__close'));cancelOpenRaf();openRaf=requestAnimationFrame(function():void{openRaf=0;if(activeModal===modal){modal.classList.add('is-visible');M.open(modal,link);}});}
function eventElement(event:Event):Element|null{return event.target instanceof Element?event.target:null;}
function onClick(event:MouseEvent):void{var target=eventElement(event),close=target?target.closest<HTMLElement>('.sc-product-modal__close'):null;if(close&&activeModal&&activeModal.contains(close)){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();closeModal();return;}var link=target?target.closest<HTMLElement>(S.productLink):null;if(!link)return;if((event.button&&event.button!==0)||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();if(closingModal&&resumeClosingModal(link))return;openModal(link);}
function onMouseDown(event:MouseEvent):void{if(!activeModal||event.target!==activeModal)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();closeModal();}
function onKeyDown(event:KeyboardEvent):void{if(!activeModal)return;if(event.key==='Escape'||event.key==='Esc'){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();closeModal();return;}if(event.key==='Tab')A.trapTab(activeModal,event);}
function onFocusIn(event:FocusEvent):void{A.containFocus(activeModal,event);}
function addListeners():void{document.addEventListener('click',onClick,true);document.addEventListener('mousedown',onMouseDown,true);document.addEventListener('keydown',onKeyDown,true);document.addEventListener('focusin',onFocusIn);}
function removeListeners():void{document.removeEventListener('click',onClick,true);document.removeEventListener('mousedown',onMouseDown,true);document.removeEventListener('keydown',onKeyDown,true);document.removeEventListener('focusin',onFocusIn);}
function init():void{if(initialized)return;initialized=true;addListeners();}
function destroy():void{if(initialized){initialized=false;removeListeners();}cancelOpenRaf();var modal=activeModal||closingModal,restore=previousFocus||closingRestore,release=releaseBackground||closingRelease||noop;activeModal=null;activeLink=null;closingModal=null;closingLink=null;previousFocus=null;releaseBackground=null;closingRelease=null;closingRestore=null;if(modal){if(M.cancel)M.cancel(modal);if(modal.parentNode)modal.parentNode.removeChild(modal);}if(document.body)document.body.classList.remove('sc-product-modal-open');release();focus(restore);}
ready(init);SC.productModal={open:openModal,close:closeModal,getActive:function():HTMLElement|null{return activeModal;},isClosing:function():boolean{return!!closingModal;},init:init,destroy:destroy};
})();
