import fs from 'node:fs';
import path from 'node:path';
import { SITE, assert, read } from '../lib/core.js';
import { type Attrs, VOID_TAGS, classSet, failList, remote, scanTags, unique, urlPath } from './shared.js';

type Budget={localScripts:string[];remoteBlockingScripts:string[];localStyles:string[];preloads:{kind:string;href:string;attrs:Attrs}[];productImages:Attrs[];bannerImages:Attrs[]};
function parseBudget(html:string):Budget{const result:Budget={localScripts:[],remoteBlockingScripts:[],localStyles:[],preloads:[],productImages:[],bannerImages:[]},stack:{name:string;classes:Set<string>}[]=[];for(const tag of scanTags(html)){if(tag.closing){for(let i=stack.length-1;i>=0;i--){if(stack[i]?.name===tag.name){stack.splice(i);break;}}continue;}const a=tag.attrs,parentClasses=new Set<string>();for(const item of stack)for(const c of item.classes)parentClasses.add(c);if(tag.name==='script'&&a.src){if(remote(a.src)){if(!Object.hasOwn(a,'async')&&!Object.hasOwn(a,'defer'))result.remoteBlockingScripts.push(a.src);}else result.localScripts.push(urlPath(a.src));}else if(tag.name==='link'){const rel=new Set((a.rel??'').toLowerCase().split(/\s+/));if(a.href&&rel.has('stylesheet')&&!remote(a.href))result.localStyles.push(urlPath(a.href));if(a.href&&rel.has('preload'))result.preloads.push({kind:(a.as??'').toLowerCase(),href:urlPath(a.href),attrs:a});}else if(tag.name==='img'){if(parentClasses.has('imgShop'))result.productImages.push(a);if(classSet(a).has('imgBannerShop'))result.bannerImages.push(a);}if(!VOID_TAGS.has(tag.name)&&!tag.raw.endsWith('/>'))stack.push({name:tag.name,classes:classSet(a)});}return result;}
export function validatePerformanceBudget(mode='pre'):void{
  assert(mode==='pre',`Unsupported performance budget mode: ${mode}`);const index=path.join(SITE,'index.html');assert(fs.existsSync(index),'Prepared Pages index is missing');const p=parseBudget(read(index)),errors:string[]=[];const expectedScripts=new Set(['js/jquery-2.1.0.min.js','_pages/legacy.js','_js_dev/main-legacy.js','override/main.js','_pages/shop.js']),expectedStyles=new Set(['_pages/legacy.css','override/main.css']);
  const scripts=new Set(p.localScripts);if(scripts.size!==expectedScripts.size||[...expectedScripts].some((value)=>!scripts.has(value)))errors.push(`local script topology changed: expected=${JSON.stringify([...expectedScripts].sort())}, actual=${JSON.stringify([...scripts].sort())}`);if(p.localScripts.length!==scripts.size)errors.push(`duplicate local script request(s): ${JSON.stringify(p.localScripts)}`);
  const styles=new Set(p.localStyles);if(styles.size!==expectedStyles.size||[...expectedStyles].some((value)=>!styles.has(value)))errors.push(`local stylesheet topology changed: expected=${JSON.stringify([...expectedStyles].sort())}, actual=${JSON.stringify([...styles].sort())}`);if(p.localStyles.length!==styles.size)errors.push(`duplicate local stylesheet request(s): ${JSON.stringify(p.localStyles)}`);if(p.remoteBlockingScripts.length)errors.push(`blocking remote scripts detected: ${JSON.stringify(p.remoteBlockingScripts)}`);
  if(!p.productImages.length)errors.push('no product images detected');else{const bad:number[]=[];p.productImages.forEach((a,i)=>{if(a.loading!=='lazy'||a.decoding!=='async'||(a.fetchpriority??'').toLowerCase()==='high')bad.push(i+1);});if(bad.length)errors.push(`product images outside lazy/async budget: ${JSON.stringify(unique(bad).slice(0,20))}`);}
  if(p.bannerImages.length!==1)errors.push(`expected exactly one catalogue banner, found ${p.bannerImages.length}`);else{const banner=p.bannerImages[0]!;if(banner.loading!=='eager'||banner.decoding!=='async'||banner.fetchpriority!=='high')errors.push('catalogue banner lost eager/async/high-priority attributes');const src=urlPath(banner.src??''),preloads=p.preloads.filter((item)=>item.kind==='image').map((item)=>item.href);if(preloads.filter((value)=>value===src).length!==1)errors.push(`catalogue banner preload mismatch: banner=${src}, image_preloads=${JSON.stringify(preloads)}`);}
  const required=[['script','_js_dev/main-legacy.js'],['style','override/main.css'],['script','override/main.js'],['font','_remote-assets/fuentes/AcuminPro-Regular.woff2'],['font','_remote-assets/fuentes/AcuminPro-Semibold.woff2']] as const,actual=new Set(p.preloads.map((item)=>`${item.kind}\0${item.href}`)),missing=required.filter(([kind,href])=>!actual.has(`${kind}\0${href}`));if(missing.length)errors.push(`missing critical preload(s): ${JSON.stringify(missing)}`);if(errors.length)failList('Pages performance budget failed',errors);
}
