import fs from 'node:fs';
import path from 'node:path';
import { SITE, assert, githubSha, read } from '../lib/core.js';
import { countLiteral, failList, scanTags, unique, urlPath } from './shared.js';

export function validateSystemLoad():void{
  const index=path.join(SITE,'index.html'),sha=githubSha();assert(fs.existsSync(index),'invalid system-load validation context');const html=read(index),scripts:string[]=[],styles:string[]=[],images:string[]=[],preloads:string[]=[];
  for(const tag of scanTags(html)){if(tag.closing)continue;const a=tag.attrs;if(tag.name==='script'&&a.src)scripts.push(a.src);else if(tag.name==='link'){const rel=new Set((a.rel??'').toLowerCase().split(/\s+/));if(rel.has('stylesheet')&&a.href)styles.push(a.href);if(rel.has('preload')&&a.href)preloads.push(a.href);}else if(tag.name==='img'&&a.src)images.push(a.src);}
  const issues:string[]=[],logo=`_critical-media/sushiclub-logo.svg?v=${sha}`;if(images.filter((value)=>value===logo).length!==2||preloads.filter((value)=>value===logo).length!==1)issues.push(`system logo load contract mismatch: images=${images.filter((value)=>value===logo).length} preloads=${preloads.filter((value)=>value===logo).length}`);
  for(const stale of ['web-sushiclub2_black_m2','web-sushiclub2_black.png','_critical-media/mobile-logo.png','_critical-media/mobile-logo.webp','_chrome-media/desktop-logo.webp'])if(html.includes(stale))issues.push(`superseded logo reference remains active/generated: ${stale}`);for(const stale of [path.join(SITE,'_critical-media/mobile-logo.png'),path.join(SITE,'_critical-media/mobile-logo.webp'),path.join(SITE,'_chrome-media/desktop-logo.webp')])if(fs.existsSync(stale))issues.push(`superseded logo file remains in artifact: ${path.relative(SITE,stale).replaceAll(path.sep,'/')}`);
  const traitTags=[...html.matchAll(/<img\b(?=[^>]*\bdata-original-title=)[^>]*>/gi)].map((match)=>match[0]);if(!traitTags.length)issues.push('legacy trait metadata nodes are missing');if(traitTags.some((tag)=>/\bsrc\s*=/.test(tag)))issues.push('legacy trait metadata still has an active img src');for(const stale of ['https://www.sushiclub.com.ar/gfx/back_body_01.png','https://www.sushiclub.com.ar/gfx/back_body_01_white.png','https://www.sushiclub.com.ar/gfx/scrollTab2.png'])if(html.includes(stale))issues.push(`superseded CSS raster remains in final browser graph: ${stale}`);
  const manifest="A=['js/jquery-2.1.0.min.js','_pages/php-guard.js?v='+S,'_pages/legacy.js?v='+S,'_js_dev/main-legacy.js?v='+S,'override/main.js?v='+S,'_pages/shop.js?v='+S]";if(countLiteral(html,manifest)!==1)issues.push(`optimized deferred runtime manifest count must be 1, found ${countLiteral(html,manifest)}`);if(!fs.existsSync(path.join(SITE,'_pages/php-guard.js')))issues.push('static Pages PHP transport guard is missing');if(html.includes('keepSessionAlive')||html.includes('keepalive: 1'))issues.push('captured PHP session keepalive remains in final Pages HTML');if(countLiteral(html,"'_pages/php-guard.js?v='+S")!==1)issues.push('PHP transport guard runtime reference is missing or duplicated');if(countLiteral(html,"c.href='_pages/deferred.css?v='+S")!==1)issues.push('optimized deferred stylesheet loader is missing or duplicated');for(const source of ['js/funcionesShop__q_f352afe3.js','js/main_shop__q_a48cd660.js'])if(html.includes(source))issues.push(`superseded shop script is still referenced by browser load graph: ${source}`);
  const stylePaths=styles.map(urlPath);for(const value of stylePaths)if(value.startsWith('_css_dev/')||['_pages/legacy.css','override/main.css','css/styles_shop__q_a48cd660.css','css/_aux__q_a48cd660.css'].includes(value))issues.push(`superseded stylesheet is still loaded directly: ${value}`);for(const value of unique(stylePaths).sort())if(stylePaths.filter((item)=>item===value).length>1)issues.push(`duplicate eager stylesheet load (${stylePaths.filter((item)=>item===value).length}x): ${value}`);if(countLiteral(html,'id="sc-pages-critical-css"')!==1)issues.push('critical inline CSS block missing or duplicated');const scriptPaths=scripts.map(urlPath);for(const value of unique(scriptPaths).sort())if(scriptPaths.filter((item)=>item===value).length>1)issues.push(`duplicate eager script load (${scriptPaths.filter((item)=>item===value).length}x): ${value}`);if(html.includes('aniversario_banner_desktop_(1)1782398717_556.webp'))issues.push('upstream banner remains referenced after responsive localization');if(!html.includes(`_critical-media/desktop-banner.webp?v=${sha}`))issues.push('optimized desktop banner reference missing');if(!html.includes(`_critical-media/mobile-banner.webp?v=${sha}`))issues.push('optimized mobile banner reference missing');if(issues.length)failList('System load validation failed',issues);
}
