(function(){
'use strict';
var SC=window.SCOverride,CFG=SC&&SC.config,C=SC&&SC.catalogTools;if(!SC||!CFG||!C||SC.__catalogStateMotionBooted)return;SC.__catalogStateMotionBooted=true;
var PRESS=CFG.motion&&CFG.motion.press||{},PRESS_GROW=Number(PRESS.grow)||.45,MIN_PRESS=Number(PRESS.minimum)||.225,TOUCH_DELAY=Number(PRESS.touchDelay)||.15,ONSET=Number(PRESS.onset)||.105,RELEASE=Number(PRESS.release)||.375,ORIGIN_SCALE=Number(PRESS.originScale)||.2,PADDING=Number(PRESS.padding)||10,SOFT_MIN=Number(PRESS.softMinimum)||75,SOFT_RATIO=Number(PRESS.softRatio)||.35,FORCED=CFG.queries&&CFG.queries.forcedColors?CFG.queries.forcedColors:matchMedia('(forced-colors: active)');
var SELECTOR='.sc-theme-toggle,.sc-catalog-view-toggle,.sc-theme-option,.sc-filter-chip,.sc-catalog-search-clear,.sc-rail-arrow,.sc-category-submenu-link,.slicknav_btn,.sc-product-modal__close,.sc-product-modal__cart-button,.productoShop .sumar,.wrapp-nav-tabsTopShop a.anchorLink,.wtopShopMenuMobile a.anchorLink';
var INWARD_FOCUS='.sc-theme-option,.sc-category-submenu-link,.wrapp-nav-tabsTopShop a.anchorLink,.wtopShopMenuMobile a.anchorLink';
function disabled(node){return!!(node.disabled||node.getAttribute('aria-disabled')==='true');}
function bind(control,gsap){if(!control||!gsap||control.__scStateMotionCleanup)return control&&control.__scStateMotionCleanup||function(){};var focusRing=document.createElement('span'),surface=document.createElement('span'),wave=document.createElement('span'),state='inactive',pressEvent=null,touchTimer=0,endTimer=0,grow=null,onset=null,release=null,startAt=0,token=0,destroyed=false;focusRing.className='sc-motion-focus-ring';focusRing.setAttribute('aria-hidden','true');if(control.matches&&control.matches(INWARD_FOCUS))focusRing.setAttribute('data-sc-focus-inward','');surface.className='sc-motion-state-surface';surface.setAttribute('aria-hidden','true');wave.className='sc-motion-state-wave';surface.appendChild(wave);control.insertBefore(surface,control.firstChild);control.insertBefore(focusRing,control.firstChild);control.classList.add('sc-motion-state-host');
function clearTouchTimer(){if(touchTimer){clearTimeout(touchTimer);touchTimer=0;}}
function clearEndTimer(){if(endTimer){clearTimeout(endTimer);endTimer=0;}}
function stopVisual(){if(grow){grow.kill();grow=null;}if(onset){onset.kill();onset=null;}if(release){release.kill();release=null;}}
function reset(){stopVisual();gsap.set(wave,{clearProps:'width,height,x,y,scale,opacity,willChange'});startAt=0;}
function zoom(){var value=Number(surface.currentCSSZoom);return isFinite(value)&&value>0?value:1;}
function geometry(event){var rect=surface.getBoundingClientRect(),width=rect.width,height=rect.height,z=zoom(),maxDim=Math.max(width,height),initial=Math.max(1,Math.floor((maxDim*ORIGIN_SCALE)/z)),soft=Math.max(SOFT_RATIO*maxDim,SOFT_MIN),radius=Math.sqrt(width*width+height*height)+PADDING,scale=((radius+soft)/initial)/z,px=width/z/2,py=height/z/2;if(event&&typeof event.pageX==='number'){px=(event.pageX-(window.scrollX+rect.left))/z;py=(event.pageY-(window.scrollY+rect.top))/z;}return{size:initial,scale:scale,startX:px-initial/2,startY:py-initial/2,endX:(width/z-initial)/2,endY:(height/z-initial)/2};}
function pressedOpacity(){var value=parseFloat(getComputedStyle(control).getPropertyValue('--sc-state-pressed-opacity'));return isFinite(value)?value:.12;}
function start(event){if(destroyed||disabled(control)||FORCED.matches)return;var id=++token,current=parseFloat(getComputedStyle(wave).opacity);if(!isFinite(current))current=0;clearEndTimer();stopVisual();var g=geometry(event),ease=SC.motion.curve('standard');startAt=performance.now()/1000;gsap.set(wave,{width:g.size,height:g.size,x:g.startX,y:g.startY,scale:1,opacity:current,willChange:'transform,opacity'});onset=gsap.to(wave,{opacity:pressedOpacity(),duration:ONSET,ease:'none',overwrite:'auto',onComplete:function(){if(id===token)onset=null;}});grow=gsap.to(wave,{x:g.endX,y:g.endY,scale:g.scale,duration:PRESS_GROW,ease:ease,overwrite:'auto',onComplete:function(){if(id===token)grow=null;}});}
function finish(){if(destroyed||!startAt||FORCED.matches)return;var id=token,elapsed=performance.now()/1000-startAt,wait=Math.max(0,MIN_PRESS-elapsed);clearEndTimer();endTimer=setTimeout(function(){endTimer=0;if(id!==token||destroyed||FORCED.matches)return;if(onset){onset.kill();onset=null;}release=gsap.to(wave,{opacity:0,duration:RELEASE,ease:'none',overwrite:'auto',onComplete:function(){if(id!==token)return;release=null;reset();}});},wait*1000);}
function isTouch(event){return event.pointerType==='touch';}
function shouldReact(event){if(FORCED.matches||disabled(control)||event.isPrimary===false)return false;if(pressEvent&&pressEvent.pointerId!==event.pointerId)return false;if(event.type==='pointerenter'||event.type==='pointerleave')return!isTouch(event);return isTouch(event)||event.buttons===1;}
function showFocus(){if(control.matches&&control.matches(':focus-visible'))control.classList.add('sc-motion-focus-visible');}
function hideFocus(){control.classList.remove('sc-motion-focus-visible');}
function pointerEnter(event){if(!shouldReact(event))return;control.classList.add('sc-motion-hovered');}
function pointerDown(event){hideFocus();if(!shouldReact(event))return;pressEvent=event;if(!isTouch(event)){state='waiting';start(event);return;}state='touchDelay';clearTouchTimer();touchTimer=setTimeout(function(){touchTimer=0;if(state!=='touchDelay')return;state='holding';start(event);},TOUCH_DELAY*1000);}
function pointerUp(event){if(!shouldReact(event))return;if(state==='holding'){state='waiting';return;}if(state==='touchDelay'){clearTouchTimer();state='waiting';start(pressEvent);}}
function click(){if(FORCED.matches||disabled(control))return;if(state==='waiting'){state='inactive';pressEvent=null;finish();return;}if(state==='inactive'){start(null);finish();}}
function pointerCancel(event){if(!shouldReact(event))return;clearTouchTimer();state='inactive';pressEvent=null;finish();}
function pointerLeave(event){if(!shouldReact(event))return;control.classList.remove('sc-motion-hovered');if(state!=='inactive'){clearTouchTimer();state='inactive';pressEvent=null;finish();}}
function contextMenu(){if(FORCED.matches||disabled(control))return;clearTouchTimer();state='inactive';pressEvent=null;finish();}
control.addEventListener('focusin',showFocus);control.addEventListener('focusout',hideFocus);control.addEventListener('pointerenter',pointerEnter);control.addEventListener('pointerdown',pointerDown);control.addEventListener('pointerup',pointerUp);control.addEventListener('pointercancel',pointerCancel);control.addEventListener('pointerleave',pointerLeave);control.addEventListener('contextmenu',contextMenu);control.addEventListener('click',click);var cleanup=function(){if(destroyed)return;destroyed=true;clearTouchTimer();clearEndTimer();control.removeEventListener('focusin',showFocus);control.removeEventListener('focusout',hideFocus);control.removeEventListener('pointerenter',pointerEnter);control.removeEventListener('pointerdown',pointerDown);control.removeEventListener('pointerup',pointerUp);control.removeEventListener('pointercancel',pointerCancel);control.removeEventListener('pointerleave',pointerLeave);control.removeEventListener('contextmenu',contextMenu);control.removeEventListener('click',click);control.classList.remove('sc-motion-hovered','sc-motion-focus-visible');reset();control.classList.remove('sc-motion-state-host');if(focusRing.parentNode)focusRing.parentNode.removeChild(focusRing);if(surface.parentNode)surface.parentNode.removeChild(surface);control.__scStateMotionCleanup=null;};control.__scStateMotionCleanup=cleanup;return cleanup;}
function install(){var alive=true,cleaners=[],observer=null;function mountNode(node,gsap){if(!node||node.nodeType!==1)return;if(node.matches&&node.matches(SELECTOR))cleaners.push(bind(node,gsap));if(node.querySelectorAll)[].slice.call(node.querySelectorAll(SELECTOR)).forEach(function(control){cleaners.push(bind(control,gsap));});}function mount(deps){if(!alive||!deps||!deps.gsap)return;mountNode(document.body,deps.gsap);if(window.MutationObserver&&document.body){observer=new MutationObserver(function(mutations){mutations.forEach(function(mutation){[].slice.call(mutation.addedNodes||[]).forEach(function(node){mountNode(node,deps.gsap);});});});observer.observe(document.body,{childList:true,subtree:true});}}if(!(SC.motion&&SC.motion.runLoaded&&SC.motion.runLoaded(mount))&&SC.motion&&SC.motion.whenLoaded)SC.motion.whenLoaded(mount);return function(){alive=false;if(observer)observer.disconnect();var unique=new Set(cleaners);unique.forEach(function(fn){if(fn)fn();});cleaners=[];};}
C.stateMotion={install:install};
})();