(function(){
'use strict';
var SC=window.SCOverride,CFG=SC&&SC.config,C=SC&&SC.catalogTools;
if(!SC||!CFG||!C||SC.__catalogThemeGlyphBooted)return;SC.__catalogThemeGlyphBooted=true;
var RAYS=[[12,1.2,12,3.8],[12,20.2,12,22.8],[1.2,12,3.8,12],[20.2,12,22.8,12],[4.35,4.35,6.18,6.18],[17.82,17.82,19.65,19.65],[17.82,6.18,19.65,4.35],[4.35,19.65,6.18,17.82]],fine=matchMedia('(hover:hover) and (pointer:fine)'),compact=matchMedia('(max-width:992px)'),deps=null,timeline=null,token=0,hoverTween=null,openTween=null;
function reduce(){return!!(CFG.queries&&CFG.queries.reducedMotion&&CFG.queries.reducedMotion.matches);}
function parts(root){var h=root&&root.querySelector('[data-sc-theme-icon]');if(!h)return null;var r=h.querySelector('[data-sc-theme-rays]'),b=h.querySelector('[data-sc-theme-bite]'),a=h.querySelector('[data-sc-theme-auto-cut]'),o=h.querySelector('[data-sc-theme-ring]'),n=[].slice.call(h.querySelectorAll('[data-sc-ray]'));return r&&b&&a&&o&&n.length===8?{host:h,rays:r,bite:b,auto:a,ring:o,lines:n}:null;}
function attrs(n,v){Object.keys(v).forEach(function(k){n.setAttribute(k,String(v[k]));});}
function ray(i,on){var r=RAYS[i],mx=(r[0]+r[2])/2,my=(r[1]+r[3])/2;return on?{x1:r[0],y1:r[1],x2:r[2],y2:r[3]}:{x1:mx,y1:my,x2:mx,y2:my};}
function kill(root){token++;if(timeline){try{timeline.kill();}catch(_){}timeline=null;}var p=parts(root),g=deps&&deps.gsap;if(g&&p)g.killTweensOf([p.rays,p.bite,p.auto,p.ring].concat(p.lines));if(root)root.removeAttribute('data-sc-theme-animating');return token;}
function stopHover(root,reset){if(hoverTween){try{hoverTween.kill();}catch(_){}hoverTween=null;}var p=parts(root),g=deps&&deps.gsap;if(reset&&p&&g)hoverTween=g.to(p.host,{rotation:0,duration:.18,ease:'power2.out',overwrite:'auto',onComplete:function(){hoverTween=null;}});}
function stopOpen(root,reset){if(openTween){try{openTween.kill();}catch(_){}openTween=null;}var p=parts(root),g=deps&&deps.gsap;if(reset&&p&&g)g.to(p.host,{rotation:0,duration:.18,ease:'power2.out',overwrite:'auto'});}
function set(root,mode){var p=parts(root);if(!p)return;kill(root);stopHover(root,false);stopOpen(root,false);p.host.style.setProperty('display','block','important');p.host.style.setProperty('visibility','visible','important');p.host.style.setProperty('opacity','1','important');p.host.style.setProperty('color','var(--sc-color-ink,#0a0a0a)','important');p.host.style.transform='rotate(0deg)';p.rays.style.opacity=mode==='light'?'1':'0';p.ring.style.opacity=mode==='system'?'1':'0';attrs(p.bite,{r:mode==='dark'?5.65:0});attrs(p.auto,mode==='system'?{x:11.15,width:1.7}:{x:12,width:0});p.lines.forEach(function(n,i){attrs(n,ray(i,mode==='light'));});p.host.setAttribute('data-sc-theme-glyph-state',mode);}
function lineTween(tl,n,i,on,pos,dur,ease){tl.to(n,{duration:dur,ease:ease,attr:ray(i,on),overwrite:'auto'},pos);}
function animate(root,from,to){var p=parts(root),g=deps&&deps.gsap;if(!p||!g||from===to){set(root,to);return;}stopHover(root,false);stopOpen(root,false);var id=kill(root),short=reduce(),retract=short?.09:.16,shape=short?.12:.18,settle=short?.08:.14,pos=0;root.setAttribute('data-sc-theme-animating','true');p.host.setAttribute('data-sc-theme-glyph-state',to);timeline=g.timeline({onComplete:function(){if(id!==token)return;timeline=null;root.removeAttribute('data-sc-theme-animating');set(root,to);if(root.querySelector('.sc-theme-toggle[aria-expanded="true"]'))open(root,true,to);}});
if(from==='light'){p.rays.style.opacity='1';p.lines.forEach(function(n,i){lineTween(timeline,n,i,false,pos,retract,'power2.in');});timeline.to(p.rays,{opacity:0,duration:retract*.72,ease:'power2.in',overwrite:'auto'},pos+retract*.28);pos+=retract;}else if(from==='dark'){timeline.to(p.bite,{duration:shape,ease:'power3.out',attr:{r:0},overwrite:'auto'},pos);pos+=shape;}else{timeline.to(p.auto,{duration:shape,ease:'power2.in',attr:{x:12,width:0},overwrite:'auto'},pos).to(p.ring,{opacity:0,duration:shape*.72,ease:'power2.in',overwrite:'auto'},pos);pos+=shape;}
if(to==='light'){p.rays.style.opacity='0';timeline.to(p.rays,{opacity:1,duration:shape*.72,ease:'power3.out',overwrite:'auto'},pos);p.lines.forEach(function(n,i){lineTween(timeline,n,i,true,pos,shape,'power3.out');});pos+=shape;}else if(to==='dark'){timeline.to(p.bite,{duration:shape,ease:'power2.inOut',attr:{r:5.65},overwrite:'auto'},pos);pos+=shape;}else{timeline.to(p.ring,{opacity:1,duration:shape*.72,ease:'power3.out',overwrite:'auto'},pos).to(p.auto,{duration:shape,ease:'power2.inOut',attr:{x:11.15,width:1.7},overwrite:'auto'},pos);pos+=shape;}
timeline.to(p.host,{rotation:0,duration:settle,ease:'power3.out',overwrite:'auto'},Math.max(0,pos-settle*.35));}
function hover(root,on){if(!fine.matches||!deps||!deps.gsap)return;var p=parts(root);if(!p||root.getAttribute('data-sc-theme-animating')==='true')return;stopHover(root,false);hoverTween=deps.gsap.to(p.host,{rotation:on?22:0,duration:.18,ease:'power2.out',overwrite:'auto',onComplete:function(){hoverTween=null;}});}
function open(root,on,mode){if(!deps||!deps.gsap)return;if(!on){stopOpen(root,true);return;}if(fine.matches&&!compact.matches)return;var p=parts(root);if(!p||root.getAttribute('data-sc-theme-animating')==='true')return;stopOpen(root,false);openTween=mode==='dark'?deps.gsap.to(p.host,{rotation:8,duration:.55,ease:'sine.inOut',yoyo:true,repeat:-1,overwrite:'auto'}):deps.gsap.to(p.host,{rotation:'+=360',duration:2.8,ease:'none',repeat:-1,overwrite:'auto'});}
function cancel(root){kill(root);stopHover(root,false);stopOpen(root,false);}
if(SC.motion&&SC.motion.whenLoaded)SC.motion.whenLoaded(function(d){deps=d;});else if(SC.motion&&SC.motion.whenReady)SC.motion.whenReady(function(d){deps=d;});
C.themeGlyph={set:set,animate:animate,hover:hover,open:open,cancel:cancel};
})();