(function(){
'use strict';

var SC=window.SCOverride,CFG=SC&&SC.config,C=SC&&SC.catalogTools;
if(!SC||!CFG||SC.__catalogToolsViewBooted)return;
SC.__catalogToolsViewBooted=true;

type CatalogViewMode='compact'|'list';
type CatalogViewContext='phone'|'tablet'|'desktop';
type ViewIconKey='grid'|'list';
type OffsetPair=readonly [number,number];
type ViewIconHost=SVGElement;

var MODES:readonly CatalogViewMode[]=['compact','list'];
var STORE_KEY='scCatalogView:v3',doc=document.documentElement,phone=CFG.queries.phone,tablet=CFG.queries.compactWide,raf=0,settleTimer=0,cleanup:(()=>void)|null=null,engine:MotionEngine|null=null;
var SHAPE_ATTRS=['x','y','width','height','rx','ry'] as const;

function context():CatalogViewContext{return phone.matches?'phone':tablet.matches?'tablet':'desktop';}
function normalize(mode:string):CatalogViewMode|''{if(mode==='normal')return'compact';return mode==='compact'||mode==='list'?mode:'';}
function selectedMode():CatalogViewMode{return normalize(doc.getAttribute('data-sc-catalog-view')||'')||'compact';}
function legacyMode(mode:string):CatalogViewMode|''{return mode==='list'?'list':mode?'compact':'';}
function columns():number{var ctx=context();return ctx==='phone'?2:ctx==='tablet'?3:4;}
function effectiveMode(mode:string):CatalogViewMode{return normalize(mode)||'compact';}
function label(mode:string):string{var effective=effectiveMode(mode),count;if(effective==='list')return'Vista lista. Cambiar a grilla de alta densidad';count=columns();return'Vista grilla de alta densidad: '+count+' '+(count===1?'columna':'columnas')+'. Cambiar a vista lista';}
function iconKey(mode:string):ViewIconKey{return effectiveMode(mode)==='list'?'list':'grid';}
function load():CatalogViewMode{var mode=normalize(doc.getAttribute('data-sc-catalog-view')||''),ctx=context(),legacy='';if(mode)return mode;try{mode=normalize(localStorage.getItem(STORE_KEY)||'');if(!mode){legacy=localStorage.getItem('scCatalogView:v2:'+ctx)||localStorage.getItem(ctx==='desktop'?'scCatalogView:desktop':'scCatalogView:mobile')||'';mode=legacyMode(legacy);if(mode){try{localStorage.setItem(STORE_KEY,mode);}catch(_){}}}}catch(_){mode='';}return mode||'compact';}
function save(mode:CatalogViewMode):void{try{localStorage.setItem(STORE_KEY,mode);}catch(_){} }
function reducedMotion():boolean{return!!(CFG.queries&&CFG.queries.reducedMotion&&CFG.queries.reducedMotion.matches);}

function liveShapes(host:ViewIconHost|null):SVGRectElement[]{return host?Array.from(host.querySelectorAll<SVGRectElement>('[data-sc-view-shape]')):[];}
function targetShapes(host:ViewIconHost,key:ViewIconKey):(SVGRectElement|null)[]{return liveShapes(host).map(function(_,index){return host.querySelector<SVGRectElement>('[data-sc-view-target="'+key+'-'+index+'"]');});}
function ensureHostPresentation(host:ViewIconHost|null):void{if(!host)return;host.style.setProperty('display','block','important');host.style.setProperty('visibility','visible','important');host.style.setProperty('color','var(--sc-color-ink,#0a0a0a)','important');host.style.setProperty('fill','var(--sc-color-ink,#0a0a0a)','important');var live=host.querySelector<SVGElement>('[data-sc-view-live]');if(live){live.style.setProperty('display','inline','important');live.style.setProperty('visibility','visible','important');}var targets=host.querySelector<SVGElement>('.sc-view-icon-targets');if(targets){targets.style.setProperty('visibility','hidden','important');targets.style.setProperty('opacity','0','important');targets.style.setProperty('pointer-events','none','important');}liveShapes(host).forEach(function(shape){shape.style.setProperty('display','inline','important');shape.style.setProperty('visibility','visible','important');shape.style.setProperty('fill','var(--sc-color-ink,#0a0a0a)','important');});}
function clearViewIconMotion(host:ViewIconHost|null):void{if(!host)return;var handles=host.__scViewIconMotion;if(handles)handles.forEach(function(handle){handle.cancel();});host.__scViewIconMotion=null;host.removeAttribute('data-sc-view-icon-animating');ensureHostPresentation(host);}
function setShapeState(host:ViewIconHost,key:ViewIconKey):void{clearViewIconMotion(host);ensureHostPresentation(host);var live=liveShapes(host),targets=targetShapes(host,key);live.forEach(function(shape,index){var target=targets[index];if(!target)return;var targetShape=target;SHAPE_ATTRS.forEach(function(attr){var value=targetShape.getAttribute(attr);if(value===null)shape.removeAttribute(attr);else shape.setAttribute(attr,value);});shape.style.removeProperty('transform');shape.style.removeProperty('will-change');});host.setAttribute('data-sc-icon-state',key);}
function targetNumbers(target:SVGRectElement):Record<string,number>{var result:Record<string,number>={};SHAPE_ATTRS.forEach(function(attr){var value=parseFloat(target.getAttribute(attr)||'0');result[attr]=Number.isFinite(value)?value:0;});return result;}
function animateIconGeometry(host:ViewIconHost|null,from:ViewIconKey,to:ViewIconKey):void{
  if(!host||from===to){if(host){host.setAttribute('data-sc-icon-state',to);ensureHostPresentation(host);}return;}if(!engine){if(host)setShapeState(host,to);return;}clearViewIconMotion(host);var live=liveShapes(host),targets=targetShapes(host,to),short=reducedMotion(),duration=short?.1:.19,ease=short?'quad.inOut':'cubic.inOut';if(!live.length||targets.some(function(target){return!target;})){setShapeState(host,to);return;}host.setAttribute('data-sc-icon-state',to);host.setAttribute('data-sc-view-icon-animating','true');var handles:MotionHandle[]=[],remaining=live.length;host.__scViewIconMotion=handles;live.forEach(function(shape,index){var target=targets[index];if(!target)return;var targetShape=target,delay=short?0:Math.floor(index/2)*.008,handle=engine!.attributes(shape,targetNumbers(targetShape),{duration:duration,delay:delay,ease:ease,onComplete:function(){remaining--;if(remaining>0||host.__scViewIconMotion!==handles)return;host.__scViewIconMotion=null;host.removeAttribute('data-sc-view-icon-animating');ensureHostPresentation(host);}});handles.push(handle);});
}
function sync(root:HTMLElement|null,mode:string,animate?:boolean):void{var button=root&&root.querySelector<HTMLButtonElement>('.sc-catalog-view-toggle'),host=button&&button.querySelector<ViewIconHost>('[data-sc-view-icon]'),key=iconKey(mode),text=label(mode),previous=host&&host.getAttribute('data-sc-icon-state');if(button){button.setAttribute('aria-label',text);button.setAttribute('title',text);button.style.setProperty('visibility','visible','important');button.style.setProperty('color','var(--sc-color-ink,#0a0a0a)','important');}if(!host)return;ensureHostPresentation(host);if(previous===key)return;if(animate!==false&&(previous==='grid'||previous==='list'))animateIconGeometry(host,previous,key);else setShapeState(host,key);}

function bindViewMicroInteraction(button:HTMLButtonElement,host:ViewIconHost):()=>void{
  if(!engine)return function(){};var shapes=liveShapes(host),handles:MotionHandle[]=[],hover=false,focus=false,pressed=false,destroyed=false;if(shapes.length!==6)return function(){};
  var hoverOffsets:OffsetPair[]=[[.58,.38],[-.58,.38],[.58,0],[-.58,0],[.58,-.38],[-.58,-.38]],pressOffsets:OffsetPair[]=[[.82,.52],[-.82,.52],[.82,0],[-.82,0],[.82,-.52],[-.82,-.52]],homeOffsets:OffsetPair[]=[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]];
  function focusVisible():boolean{try{return button.matches(':focus-visible');}catch(_){return document.activeElement===button;}}
  function stop():void{handles.forEach(function(handle){handle.cancel();});handles=[];}
  function apply(offsets:readonly OffsetPair[],duration:number,ease:string):void{if(destroyed)return;stop();if(reducedMotion()){shapes.forEach(function(shape){shape.style.removeProperty('transform');shape.style.removeProperty('will-change');});return;}shapes.forEach(function(shape,index){var o=offsets[index]||[0,0];handles.push(engine!.transform(shape,{x:o[0],y:o[1]},{duration:duration,delay:index*.004,ease:ease,onComplete:function(){shape.style.removeProperty('will-change');}}));});}
  function active():void{apply(hoverOffsets,.068,'quart.out');}function home():void{apply(homeOffsets,.09,'quart.out');}function press():void{apply(pressOffsets,.042,'cubic.out');}
  function enter(e:PointerEvent):void{if(e.pointerType==='touch')return;hover=true;if(!pressed)active();}function leave():void{hover=false;pressed=false;if(focus)active();else home();}function down():void{pressed=true;press();}function up():void{pressed=false;if(hover||focus)active();else home();}function focusIn():void{if(focusVisible()){focus=true;if(!pressed)active();}}function focusOut():void{focus=false;pressed=false;if(hover)active();else home();}function keyDown(e:KeyboardEvent):void{if(e.repeat||(e.key!=='Enter'&&e.key!==' '))return;pressed=true;press();}function keyUp(e:KeyboardEvent):void{if(e.key!=='Enter'&&e.key!==' ')return;pressed=false;if(hover||focus)active();else home();}
  button.addEventListener('pointerenter',enter);button.addEventListener('pointerleave',leave);button.addEventListener('pointerdown',down);button.addEventListener('pointerup',up);button.addEventListener('pointercancel',leave);button.addEventListener('focus',focusIn);button.addEventListener('blur',focusOut);button.addEventListener('keydown',keyDown);button.addEventListener('keyup',keyUp);
  return function(){if(destroyed)return;destroyed=true;button.removeEventListener('pointerenter',enter);button.removeEventListener('pointerleave',leave);button.removeEventListener('pointerdown',down);button.removeEventListener('pointerup',up);button.removeEventListener('pointercancel',leave);button.removeEventListener('focus',focusIn);button.removeEventListener('blur',focusOut);button.removeEventListener('keydown',keyDown);button.removeEventListener('keyup',keyUp);stop();shapes.forEach(function(shape){shape.style.removeProperty('transform');shape.style.removeProperty('will-change');});};
}

function refreshMotionNow():void{if(SC.motion)SC.motion.refresh(0);}
function syncMounted():void{var root=document.querySelector<HTMLElement>('.sc-catalog-tools');if(root)sync(root,selectedMode(),false);}
function refreshLayout(switching:boolean):void{syncMounted();if(raf)cancelAnimationFrame(raf);if(settleTimer){clearTimeout(settleTimer);settleTimer=0;}raf=requestAnimationFrame(function(){raf=requestAnimationFrame(function(){raf=0;if(SC.productCardContent&&SC.productCardContent.scheduleDescriptionMeasure)SC.productCardContent.scheduleDescriptionMeasure();refreshMotionNow();if(switching){settleTimer=window.setTimeout(function(){settleTimer=0;doc.classList.remove('sc-catalog-view-switching');},80);}});});}
function apply(root:HTMLElement,mode:string,persist:boolean):void{var normalized=normalize(mode)||'compact';if(persist)doc.classList.add('sc-catalog-view-switching');doc.setAttribute('data-sc-catalog-view',normalized);document.body.setAttribute('data-sc-catalog-view',normalized);root.setAttribute('data-sc-view',normalized);sync(root,normalized,persist);if(persist)save(normalized);refreshLayout(persist);}
function destroy():void{var host=document.querySelector<ViewIconHost>('.sc-catalog-view-toggle [data-sc-view-icon]');if(host)clearViewIconMotion(host);if(raf){cancelAnimationFrame(raf);raf=0;}if(settleTimer){clearTimeout(settleTimer);settleTimer=0;}doc.classList.remove('sc-catalog-view-switching');if(cleanup){var fn=cleanup;cleanup=null;fn();}}
function install(root:HTMLElement):()=>void{destroy();var button=root.querySelector<HTMLButtonElement>('.sc-catalog-view-toggle'),host=button&&button.querySelector<ViewIconHost>('[data-sc-view-icon]');if(!button||!host)return function(){};button.style.setProperty('visibility','visible','important');button.style.setProperty('color','var(--sc-color-ink,#0a0a0a)','important');ensureHostPresentation(host);apply(root,load(),false);var microCleanup=bindViewMicroInteraction(button,host);function click():void{var current=selectedMode();apply(root,current==='compact'?'list':'compact',true);}function breakpoint():void{refreshLayout(false);}button.addEventListener('click',click);if(phone.addEventListener)phone.addEventListener('change',breakpoint);else phone.addListener(breakpoint);if(tablet.addEventListener)tablet.addEventListener('change',breakpoint);else tablet.addListener(breakpoint);var mountedButton=button;cleanup=function(){microCleanup();mountedButton.removeEventListener('click',click);if(phone.removeEventListener)phone.removeEventListener('change',breakpoint);else phone.removeListener(breakpoint);if(tablet.removeEventListener)tablet.removeEventListener('change',breakpoint);else tablet.removeListener(breakpoint);};var ownCleanup=cleanup;return function(){if(cleanup===ownCleanup)destroy();};}

if(SC.motion&&typeof SC.motion.whenLoaded==='function')SC.motion.whenLoaded(function(deps:MotionDeps){engine=deps.engine;});else if(SC.motion&&typeof SC.motion.whenReady==='function')SC.motion.whenReady(function(deps:MotionDeps){engine=deps.engine;});
C.view={install:install,apply:apply,refreshLayout:refreshLayout,sync:syncMounted,destroy:destroy};
})();
