(function(){
'use strict';
var SC=window.SCOverride,U=SC&&SC.utils,C=SC&&SC.config,S=C&&C.selectors,K=C&&C.classes,N=SC&&SC.categoryNav,T=SC&&SC.templates;
if(!SC||!U||!C||!N||!T||SC.__categoryNavIndicatorBooted)return;SC.__categoryNavIndicatorBooted=true;var CFG={scrollDecay:13,speedFilter:18,warpFilter:16,epsilonPosition:.06,epsilonVelocity:1.4,durationBase:.24,durationExtra:.18,durationDistance:760,durationPower:.62,omegaScale:8,minDuration:.12,minWidth:6,minTravel:18,travelWidthRatio:.55,railVelocityScale:240,speedEnergyScale:520,maxWarp:11,minWarp:4.5,warpWidthRatio:.13,directionThreshold:8,leadingShare:.92,trailingShare:.08,settleWarp:.025,settleSmoothVelocity:1.2,settleScrollVelocity:2,maxFrameDelta:.05,minFrameDelta:.001,scrollSampleMin:.003,scrollSampleMax:.16,scrollVelocityOldWeight:.32,scrollVelocityNewWeight:.68,scrollWakeMs:90,textInsetMax:1.25,textInsetRatio:.025};
var entries=[],dirty=true,raf=0,lastFrame=0;
function now(){return window.performance&&performance.now?performance.now():Date.now();}
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
function physicalPixel(){return 1/Math.max(1,window.devicePixelRatio||1);}
function floorPhysical(v){var dpr=Math.max(1,window.devicePixelRatio||1);return Math.floor(v*dpr+1e-6)/dpr;}
function mount(root){return root.closest(N.selectors.mobileScroller)||root;}
function visual(link){var fallback=link.getBoundingClientRect();try{var range=document.createRange();range.selectNodeContents(link);var rect=range.getBoundingClientRect();if(rect&&rect.width>1&&rect.height>0)return rect;}catch(_){}return fallback;}
function reduced(){return SC.motion&&SC.motion.reduced?SC.motion.reduced():C.queries.reducedMotion.matches;}
function transform(x,width){return 'translate3d('+x+'px,0,0) scaleX('+Math.max(1,width)+')';}
function scrollNode(root,host){return root.closest(N.selectors.mobileScroller+','+N.selectors.scroller)||((host.scrollWidth||0)>(host.clientWidth||0)+1?host:null);}
function sameTarget(link,target){var resolved=N.anchor(link.getAttribute('href'));if(resolved===target)return true;return !!(resolved&&target&&resolved.id&&target.id&&resolved.id===target.id);}
function rootsFor(target){var roots=[];N.links().forEach(function(link){if(!sameTarget(link,target)||!U.visible(link))return;var root=link.closest(".nav-tabsTopShop,.nav-tabs");if(root&&roots.indexOf(root)<0)roots.push(root);});return roots;}
function wake(){if(!raf){lastFrame=now();raf=requestAnimationFrame(frame);}}
function unbind(item){if(item.scrollEl&&item.onScroll)item.scrollEl.removeEventListener('scroll',item.onScroll);item.scrollEl=null;item.onScroll=null;}
function destroy(item){unbind(item);if(item.line&&item.line.parentNode)item.line.parentNode.removeChild(item.line);}
function bindScroll(item){var el=scrollNode(item.root,item.host);if(el===item.scrollEl)return;unbind(item);item.scrollEl=el;if(!el)return;item.scrollX=el.scrollLeft||0;item.scrollT=now();item.scrollV=0;item.onScroll=function(){var t=now(),x=el.scrollLeft||0,dt=(t-item.scrollT)/1000;if(dt>CFG.scrollSampleMin&&dt<CFG.scrollSampleMax){var v=-(x-item.scrollX)/dt;item.scrollV=item.scrollV*CFG.scrollVelocityOldWeight+v*CFG.scrollVelocityNewWeight;}item.scrollX=x;item.scrollT=t;item.scrollUntil=t+CFG.scrollWakeMs;wake();};el.addEventListener('scroll',item.onScroll,{passive:true});}
function entry(root){var host=mount(root),item=null;for(var i=entries.length-1;i>=0;i--){if(entries[i].root!==root)continue;if(entries[i].host===host){item=entries[i];break;}destroy(entries[i]);entries.splice(i,1);}if(!item){var line=T.clone('category-indicator');host.classList.add("sc-category-motion-root");host.appendChild(line);if(host.matches(N.selectors.mobileScroller))line.style.setProperty('bottom','0','important');item={root:root,host:host,line:line,init:false,left:0,right:1,targetLeft:0,targetRight:1,vl:0,vr:0,warp:0,smoothV:0,dir:1,duration:CFG.durationBase,scrollEl:null,onScroll:null,scrollX:0,scrollT:0,scrollV:0,scrollUntil:0};entries.push(item);}bindScroll(item);return item;}
function snap(item,left,right){item.left=item.targetLeft=left;item.right=item.targetRight=right;item.vl=item.vr=item.warp=item.smoothV=item.scrollV=0;item.line.style.opacity='1';item.line.style.transformOrigin='0 50%';item.line.style.transform=transform(left,right-left);item.init=true;}
function spring(pos,vel,target,omega,dt){var y=pos-target,c=vel+omega*y,e=Math.exp(-omega*dt),nextY=(y+c*dt)*e,nextV=(vel-omega*c*dt)*e,next=target+nextY;if(y&&(next-target)*y<0){next=target;nextV=0;}return[next,nextV];}
function durationFor(item,left,right){var from=(item.left+item.right)*.5,to=(left+right)*.5,d=Math.abs(to-from);return CFG.durationBase+CFG.durationExtra*Math.pow(Math.min(1,d/CFG.durationDistance),CFG.durationPower);}
function render(item,dt,t){
  if(!item.init)return false;if(reduced()){snap(item,item.targetLeft,item.targetRight);return false;}
  var omega=CFG.omegaScale/Math.max(CFG.minDuration,item.duration),s=spring(item.left,item.vl,item.targetLeft,omega,dt);item.left=s[0];item.vl=s[1];s=spring(item.right,item.vr,item.targetRight,omega,dt);item.right=s[0];item.vr=s[1];
  if(t>item.scrollUntil)item.scrollV*=Math.exp(-CFG.scrollDecay*dt);
  var rawV=(item.vl+item.vr)*.5+item.scrollV,velocityAlpha=1-Math.exp(-CFG.speedFilter*dt);item.smoothV+=(rawV-item.smoothV)*velocityAlpha;
  var width=Math.max(CFG.minWidth,item.targetRight-item.targetLeft),remaining=Math.abs(((item.targetLeft+item.targetRight)-(item.left+item.right))*.5),travel=clamp(remaining/Math.max(CFG.minTravel,width*CFG.travelWidthRatio),0,1),railEnergy=clamp(Math.abs(item.scrollV)/CFG.railVelocityScale,0,1),speed=Math.abs(item.smoothV),speedEnergy=speed/(speed+CFG.speedEnergyScale),envelope=Math.max(travel,railEnergy),maxWarp=Math.min(CFG.maxWarp,Math.max(CFG.minWarp,width*CFG.warpWidthRatio)),sign=speed>CFG.directionThreshold?(item.smoothV>0?1:-1):item.dir,warpTarget=sign*maxWarp*speedEnergy*envelope,warpAlpha=1-Math.exp(-CFG.warpFilter*dt);item.warp+=(warpTarget-item.warp)*warpAlpha;
  if(speed>CFG.directionThreshold)item.dir=item.smoothV>0?1:-1;
  var stretch=Math.abs(item.warp),left=item.left,right=item.right;if(item.warp>=0){left-=stretch*CFG.trailingShare;right+=stretch*CFG.leadingShare;}else{left-=stretch*CFG.leadingShare;right+=stretch*CFG.trailingShare;}
  item.line.style.opacity='1';item.line.style.transformOrigin='0 50%';item.line.style.transform=transform(left,right-left);
  var settled=Math.abs(item.left-item.targetLeft)<CFG.epsilonPosition&&Math.abs(item.right-item.targetRight)<CFG.epsilonPosition&&Math.abs(item.vl)<CFG.epsilonVelocity&&Math.abs(item.vr)<CFG.epsilonVelocity&&Math.abs(item.warp)<CFG.settleWarp&&Math.abs(item.smoothV)<CFG.settleSmoothVelocity&&Math.abs(item.scrollV)<CFG.settleScrollVelocity&&t>item.scrollUntil;
  if(settled){snap(item,item.targetLeft,item.targetRight);return false;}return true;
}
function frame(t){raf=0;var dt=clamp((t-lastFrame)/1000,CFG.minFrameDelta,CFG.maxFrameDelta);lastFrame=t;var active=false;for(var i=entries.length-1;i>=0;i--){var item=entries[i];if(!document.documentElement.contains(item.root)||!document.documentElement.contains(item.host)){destroy(item);entries.splice(i,1);continue;}bindScroll(item);if(render(item,dt,t))active=true;}if(active)wake();}
function move(target,animate){var roots=rootsFor(target);roots.forEach(function(root){var link=N.links(root).find(function(node){return sameTarget(node,target)&&U.visible(node);});if(!link)return;var item=entry(root),linkRect=visual(link),x,width,scale=1,inset;if(item.host.matches(N.selectors.mobileScroller)){var hostRect=item.host.getBoundingClientRect();x=item.host.scrollLeft+(linkRect.left-hostRect.left);width=linkRect.width;}else{var rootRect=root.getBoundingClientRect();scale=root.offsetWidth&&rootRect.width?rootRect.width/root.offsetWidth:1;if(!isFinite(scale)||scale<=0)scale=1;x=(linkRect.left-rootRect.left)/scale+(root.scrollLeft||0);width=linkRect.width/scale;}inset=Math.min(CFG.textInsetMax,Math.max(0,width*CFG.textInsetRatio));x+=inset;width=Math.max(CFG.minWidth,width-inset*2);if(item.host.matches(N.selectors.mobileScroller)){var right=floorPhysical(x+width)-physicalPixel();width=Math.max(CFG.minWidth,right-x);}var targetCenter=x+width*.5,currentCenter=(item.left+item.right)*.5,delta=targetCenter-currentCenter;if(Math.abs(delta)>CFG.epsilonPosition)item.dir=delta>0?1:-1;item.targetLeft=x;item.targetRight=x+width;item.line.style.opacity='1';item.line.style.transformOrigin='0 50%';if(!item.init||!animate||reduced())snap(item,x,x+width);else{item.duration=durationFor(item,x,x+width);wake();}});dirty=false;}
function markDirty(){dirty=true;}function isDirty(){return dirty;}
function pause(){if(raf)cancelAnimationFrame(raf);raf=0;entries.forEach(unbind);}
function resume(){for(var i=entries.length-1;i>=0;i--){var item=entries[i];if(!document.documentElement.contains(item.root)||!document.documentElement.contains(item.host)){destroy(item);entries.splice(i,1);continue;}bindScroll(item);}}
N.categoryIndicator={move:move,markDirty:markDirty,isDirty:isDirty,pause:pause,resume:resume};N.moveIndicator=move;
})();
