import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd(),read=(p:string)=>fs.readFileSync(path.join(root,p),'utf8'),errors:string[]=[];const fail=(m:string)=>errors.push(m);
const view=read('override/components/catalog-tools/view.ts'),main=read('override/main.ts'),tools=read('override/components/catalog-tools/catalog-tools.css'),list=read('override/components/catalog-tools/view-stability.css'),grid=read('override/features/catalog/layout.css');
if(!/MODES(?::[^=]+)?=\['compact','list'\]/.test(view))fail('view.ts must expose density + list only');if(/MODES[^=]*=\[[^\]]*normal/.test(view))fail('view.ts reintroduced low-density normal mode');if(!/VIEW_MODES(?::[^=]+)?=\['compact','list'\]/.test(main))fail('main.ts bootstrap must expose density + list only');if(!view.includes("if(mode==='normal')return'compact'"))fail('legacy normal preference must migrate to density');
if(/data-sc-catalog-view=['"]list['"]/.test(tools))fail('catalog-tools.css must not own list geometry');if(!tools.includes('--sc-compact-columns: 4'))fail('desktop density must default to 4 columns');if(!tools.includes('--sc-compact-columns: 3'))fail('tablet density must override to 3 columns');if(!tools.includes('--sc-compact-columns: 2'))fail('phone density must override to 2 columns');
for(const token of ['--sc-view-list-image-width: 210px','--sc-view-list-image-width: 160px','--sc-view-list-image-width: 150px'])if(!list.includes(token))fail(`Missing list token ${token}`);if(!list.includes('grid-template-columns: var(--sc-view-list-image-width) minmax(0, 1fr) !important'))fail('shared two-column list anatomy missing');if(/@media\s*\(min-width\s*:\s*993px\)/.test(list))fail('list structure must not fork into a desktop-only media block');if(!grid.includes('--sc-catalog-base-columns: 4'))fail('catalog desktop base must be 4 columns');
for(const file of ['override/components/product-card/layout.css','override/components/product-card/pricing.css','override/components/product-card/image-ratio.css','override/components/section-heading/layout.css','override/features/content-normalizer/content-normalizer.css','override/components/product-modal/motion.css'])if(/@media\s*\(min-width\s*:\s*993px\)/.test(read(file)))fail(`${file} contains a desktop-only structural fork`);
if(errors.length){console.error(`Responsive contract validation failed with ${errors.length} issue(s):`);for(const error of errors)console.error(`- ${error}`);process.exit(1);}console.log('Responsive contract validation passed.');
