/* Aparición forward-only de títulos con fade lineal por línea. */
(function(){
'use strict';
var SC=window.SCOverride,C=SC&&SC.config,S=C&&C.selectors;if(!SC||!C||!SC.motion||typeof SC.motion.whenLoaded!=='function'||SC.__sectionHeadingBooted)return;SC.__sectionHeadingBooted=true;
var initialized=false,motionDeps=null,generation=0,mutationObserver=null,elements=[],splits=[],states=new WeakMap(),RULE_PROPERTY='--sc-section-rule-scale',OPEN=.5,ITEM=.25,CFG={startPct:99,refreshDelay:60};
function ensureGate(){if(SC.catalogRevealGate)return SC.catalogRevealGate;var root=document.documentElement,gate={headings:false,cards:false,released:false};gate.release=function(){if(gate.released)return;gate.released=true;if(root){root.setAttribute('data-sc-catalog-reveal-ready','true');root.classList.remove('sc-catalog-reveal-prepaint');}};gate.mark=function(part){if(part==='headings')gate.headings=true;if(part==='cards')gate.cards=true;if(gate.headings&&gate.cards)gate.release();};return SC.catalogRevealGate=gate;}
var gate=ensureGate();
function ready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();}
function targets(){return Array.prototype.filter.call(document.querySelectorAll('.listadoShop .titleShopSeccion > div, .listadoShop .subTitleShopSeccion'),function(el){return(el.textContent||'').replace(/\s+/g,' ').trim().length>0;});}
function isParent(el){return!!(el.parentElement&&el.parentElement.classList.contains(S.sectionTitle.slice(1)));}
function host(el){return isParent(el)?el.parentElement:el;}
function headingUnit(node){if(!node||!node.matches)return null;if(node.matches(S.sectionSubtitle))return node;if(node.matches(S.sectionTitle))return node.querySelector(':scope > div');return null;}
function renderable(el){var target=host(el);return!!(target&&!target.hidden&&target.offsetParent!==null&&target.getBoundingClientRect().height>0);}
function state(el){var value=states.get(el);if(!value){value={prepared:false,done:false,split:null,tween:null,trigger:null,firstSplit:true,raf:0};states.set(el,value);}return value;}
function lines(el){var value=state(el);return value.split&&value.split.lines&&value.split.lines.length?value.split.lines:[el];}
function killTrigger(value){if(value.trigger){value.trigger.kill();value.trigger=null;}}
function clear(gsap,el){gsap.set(lines(el),{clearProps:'opacity,visibility,willChange'});if(isParent(el))gsap.set(el,{clearProps:RULE_PROPERTY});}
function finish(gsap,el){var value=state(el);if(value.done)return;value.done=true;killTrigger(value);if(value.raf){cancelAnimationFrame(value.raf);value.raf=0;}if(value.tween){value.tween.progress(1);value.tween.kill();value.tween=null;}gsap.set(lines(el),{autoAlpha:1});if(isParent(el))gsap.set(el,{[RULE_PROPERTY]:1});clear(gsap,el);}
function reveal(gsap,el){var value=state(el);if(value.done||value.tween)return;var list=lines(el),count=Math.max(1,list.length),step=(OPEN-ITEM)/count;if(isParent(el))gsap.set(el,{[RULE_PROPERTY]:1});value.tween=gsap.to(list,{autoAlpha:1,duration:ITEM,stagger:{each:step,from:'start'},ease:'none',overwrite:'auto',onComplete:function(){value.tween=null;finish(gsap,el);}});}
function armTrigger(gsap,ST,el,initialPass){var value=state(el);if(value.done||!renderable(el))return;var target=host(el),rect=target.getBoundingClientRect();killTrigger(value);if(rect.bottom<=0){finish(gsap,el);return;}if(initialPass&&rect.top<innerHeight&&rect.bottom>0){reveal(gsap,el);return;}value.trigger=ST.create({trigger:target,start:'top '+CFG.startPct+'%',once:true,onEnter:function(self){if(self.direction>0)reveal(gsap,el);else finish(gsap,el);},onEnterBack:function(){finish(gsap,el);}});}
function prepare(gsap,SplitText,ST,el){var value=state(el);if(value.prepared||!renderable(el))return;value.prepared=true;if(isParent(el)){el.classList.add('sc-section-rule-host');el.removeAttribute('aria-label');gsap.set(el,{[RULE_PROPERTY]:0});}value.split=SplitText.create(el,{type:'lines',mask:'lines',linesClass:'sc-section-text-line',autoSplit:true,aria:'none',onSplit:function(self){var first=value.firstSplit;value.firstSplit=false;value.split=self;if(value.tween)value.tween.kill();killTrigger(value);if(value.done){gsap.set(self.lines,{autoAlpha:1});if(isParent(el))gsap.set(el,{[RULE_PROPERTY]:1});return;}gsap.set(self.lines,{autoAlpha:0,willChange:'opacity'});value.raf=requestAnimationFrame(function(){value.raf=0;armTrigger(gsap,ST,el,first);});}});splits.push(value.split);}
function armNode(gsap,SplitText,ST,node){if(!node||node.hidden)return;if(node.matches&&node.matches(S.productList)){node.querySelectorAll(S.sectionTitle+','+S.sectionSubtitle).forEach(function(item){var el=headingUnit(item);if(el)prepare(gsap,SplitText,ST,el);});return;}var el=headingUnit(node);if(el)prepare(gsap,SplitText,ST,el);}
function initMotion(deps,token){var SplitText=deps&&deps.SplitText;if(initialized||token!==generation||!SplitText)return;initialized=true;var gsap=deps.gsap,ST=deps.ScrollTrigger;elements=targets();splits=[];if(SC.motion.reduced()){elements.forEach(function(el){state(el).done=true;gsap.set(el,{clearProps:'opacity,visibility'});});gate.mark('headings');return;}elements.forEach(function(el){prepare(gsap,SplitText,ST,el);});var container=document.querySelector(S.container);if(container&&window.MutationObserver){mutationObserver=new MutationObserver(function(mutations){mutations.forEach(function(mutation){if(mutation.type==='attributes'&&mutation.attributeName==='hidden'&&!mutation.target.hidden)armNode(gsap,SplitText,ST,mutation.target);});});mutationObserver.observe(container,{subtree:true,attributes:true,attributeFilter:['hidden']});}gate.mark('headings');SC.motion.refresh(CFG.refreshDelay);if(document.fonts&&document.fonts.ready)document.fonts.ready.then(function(){if(initialized&&token===generation)SC.motion.refresh(CFG.refreshDelay);}).catch(function(){});}
function init(){if(initialized||!motionDeps)return;initMotion(motionDeps,++generation);}
function destroy(){generation++;if(mutationObserver){mutationObserver.disconnect();mutationObserver=null;}if(motionDeps){var gsap=motionDeps.gsap;elements.forEach(function(el){var value=state(el);if(value.raf)cancelAnimationFrame(value.raf);if(value.tween)value.tween.kill();killTrigger(value);clear(gsap,el);el.classList.remove('sc-section-rule-host');value.prepared=false;});splits.forEach(function(split){if(split&&split.revert)split.revert();});}initialized=false;elements=[];splits=[];}
SC.sectionHeading={init:init,destroy:destroy,cleanup:destroy};SC.motion.whenLoaded(function(deps){motionDeps=deps;ready(init);});
})();